# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_app', '0002_auto_20171020_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
