# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='lasst_name',
            new_name='last_name',
        ),
    ]
