# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restful_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
