# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('reviews_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='login_app.Users'),
            preserve_default=False,
        ),
    ]
