# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0003_auto_20171019_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='reviewer',
            new_name='poster',
        ),
    ]
