# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ninjas_app', '0002_auto_20171016_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ninjas',
            name='dojos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninjas', to='ninjas_app.Dojos'),
        ),
    ]
